### ISSUE TITLE
Ako sa zapojit?

### ISSUE THREAD

**Issue by ricco386** [pyconsk/www.python.sk#1]
Spravit stranku, dokumentaciu ako sa zapojit a pomoct s tvorbou python.sk

**Comment by Pytlicek** [comment]
Ja sa do toho pustím čím skorej.

**Comment by ricco386** [comment]
Ja uz som napisal cosi, ale mozes skusit prelozit nech to mame aj v SK. Vsetko ostatne uz  mozeme robit v SK, ale toto by bolo mat fajn aj v EN ak sem niekto zabludi.
